### PR TITLE
Implement all MMX Instructions + Tests

### PR DESCRIPTION
**Pull request by afonso360**
Not ready for merge.

Implements all of the missing MMX instructions and adds a basic MMX test suite.

The PR is not ready for merge because right now, it builds the `mmx.c` file with the default compiler. Which on ARM is not going to work. We need to find a x86 compiler (native on x86, cross on ARM) and use that.

The other thing that would be cool to do would be to build the MMX suite only on `make test`. I haven't looked too much into this, but from what I've seen, people add the binary to be built on `make check`, which could be a reasonable compromise.

I'll try to find a solution tomorrow, but let me know if you know how to solve any of these issues.

### CODE REVIEW

**Comment by ptitSeb** [comment]
Yes, for testing, I simply put a precompile binary in `tests/`, along with the source file of the test, and capture of the console print from a native x86 platform. Adding the test is then easy, and is simply based on comparing console output.

**Comment by afonso360** [comment]
I don't really like the idea of having precompiled binaries on git. Especially for tests, which are probably going to be changed often. But yeah, lets do that until we have a more advanced solution.

Would you be ok with in the future requiring a cross compiler for non-x86 and a compiling before running the testsuites?

**Comment by ptitSeb** [comment]
The cross compiler would be fine, but as an option. My main developpement platform is the OpenPandora, and I don't want to have to build an x86 cross compiler on it (building gcc take 2 full day on the plateform).
But I can totally imagine an option to ignore the tests binary and build a fresh copy if cross compiler is there.
Note that, test should not change often. there are supposed to be reference test and I see no reason to change them often.

What I do need seen is to setup TravisCI here.

**Comment by afonso360** [comment]
I've pushed the reference binary to the branch. But won't be able to properly test on ARM until tommorow

**Comment by ptitSeb** [comment]
do you want me to wait you can test on ARM before merging?

**Comment by afonso360** [comment]
I don't think it will fail. But let me test it, i don't want to break testing on master

**Comment by ptitSeb** [comment]
Ok

**Comment by afonso360** [comment]
Tested it on my raspberry pi 3, everything seems to work, so if you are happy with it, please merge.

**Comment by ptitSeb** [comment]
done

**Pull request merged**
