### PR TITLE
PKGBUILDs for Arch Linux.

### PR DESCRIPTION
**Pull request by SpacingBat3**
I've added an RPi4B PKGBUILD right now, but planning for the other platforms too. Just give me an info about the `depends()` and `optdepends()` (I figured myself out which `makedepends()` are needed).

### CODE REVIEW

**Comment by ptitSeb** [comment]
looks ok to me.
As mentionned in the discord server, box86 doesn't really have dependencies.

**Comment by SpacingBat3** [comment]
OK then, it will go to the regular pull request as soon as I'll create PKGBUILDs for the other plarforms (pandora etc).

**Comment by SpacingBat3** [comment]
Ready to merge, @ptitSeb!

**Comment by SpacingBat3** [comment]
(or at least to final review)

**Pull request merged**
