### PR TITLE
WIP: Add configration file support

### PR DESCRIPTION
**Pull request by Seas0**

### CODE REVIEW

**Comment by Seas0** [comment]
Now there are 33 entries described in the USAGE.md, and keeping all the environment variables tracked is becoming an unpleasant job to do (either manually set, or export in /etc/profile.d, etc.), so I think adding a configuration file parse functionality is important to let box86 be more easier to use.

**Comment by Seas0** [comment]
Currently this PR is a dummy one, I've opened it to seek for a suggestion to configuration file parser in C, if anyone have a idea, just feel free to comment.

**Comment by ptitSeb** [comment]
I'm not sure what do you have in mind. Do you have some example of what you would like?

**Comment by Seas0** [comment]
It might be a good idea to add a configuration file like the DosBox or Bochs' ones (An unofficial example for latter: [here](https://github.com/pokitoz/bos/blob/master/bochsrc-sample.txt) ) for a easier configuration.
For Box86 I think first let all the configuration used to be done with environment variables can be achieved by a key-pair config file (May be a simple .INI file can do?)
 second make the special program treatments into some separate configs rather than hard-coded them into the main program.

**Comment by ptitSeb** [comment]
why closing the ticket?

**Comment by Seas0** [comment]
I accidently deleted the branch earlier, sorry.
The branch has been restored and I'd reopen this pr.

**Comment by Seas0** [comment]
I'm hesitating for either adding a 3rd party library (like [libconfuse](https://github.com/libconfuse/libconfuse), [libconfig](https://github.com/hyperrealm/libconfig) or [libconfini](https://github.com/madmurphy/libconfini))for configuration handling or just make a handwritten one (like in the [Bochs](https://bochs.sourceforge.io/) project). Any suggestions?

**Comment by ptitSeb** [comment]
I would prefer to not use 3rd party libs.

**Comment by ptitSeb** [comment]
This has been superceeded by the "RC" files handling. So closing it.

**Pull request closed without merging**
