### PR TITLE
Add more info about neon vfpv3 to COMPILE.md

### PR DESCRIPTION
**Pull request by mocsy**
apt install neon-support

### CODE REVIEW

**Comment by ptitSeb** [comment]
In what case did you need that package?

**Comment by mocsy** [comment]
This package gives utilities to query neon a vfpv3 cpu support.

This is on Ubuntu 23 64bit from the official Raspberry Pi 5 imager.
I enabled Dynarec and using the Pi4 profile otherwise.
Without this package the make -j4 step fails.

After installing it and rerunning cmake the compilation works.
With this I managed to start steam and tested game streaming from a Windows PC to the Pi 5.

What is strange about this is that I compiled box64 first (in hopes that wow64 would just work and I can get away without box86), which has a Pi5 profile and for some reason it didn't fail compiling.

**Comment by mocsy** [comment]
https://packages.ubuntu.com/mantic/neon-support

Maybe it's functionality is redundant with some other package that machine also didn't have.

**Comment by ptitSeb** [comment]
The video you linked was recoreded on a arm machine that have real AMD Rx550 graphic card (well, a laptop model, so 64bts bus, but still a dedicated graphic card). I don't think the PI5 GPU is as fast as this graphic card.

**Pull request merged**
